accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('send-code/', views.send_code, name='scode'),
    path('logout/', views.logout, name="logout")
    # path('profile/detail/', views.UpdateProfile.as_view(), name='profile_detail'),
]

notes/urls.py
from django.urls import path
from . import views


app_name = 'note'

urlpatterns = [
    path('', views.NoteCreateView.as_view(), name='create'),
    path('manage/', views.NotesManager.as_view(), name='manage'),
    path('update/<uuid>/', views.NoteUpdateView.as_view(), name='update'),
    path('detail/<uuid>/', views.NoteDetailView.as_view(), name='detail'),
    path('delete/', views.NoteDeleteView.as_view(), name='delete'),
    path('settings/', views.UpdateProfile.as_view(), name='settings'),
    path('find/', views.FindUsers.as_view(), name='find'),
    path('profile/<str:username>/', views.UsersProfile.as_view(), name="user-profile"),
    path('note/pub/', views.pub_note, name='pub-note'),
    path('bookmark/', views.NoteBookMark.as_view(), name='bookmark'),
    path('bookmark/add/', views.bookmark, name='add-bookmark'),
    path('stats/', views.NotesStats.as_view(), name='stats'),
    path('donate/', views.donate, name="donate"),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('bigdevil/url/admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/models.py
from django.db import models
from django.conf import settings
from .tasks import async_convert
from django.core.files import File
import uuid
import os


CODE_LANGUAGE_CHOICES = (
    (1, 'Plain Text'),
    (2, 'Programming Language Code'),
)


class BookMarked(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bookmarked')
    note = models.OneToOneField('Note', on_delete=models.CASCADE, related_name='bookmarked')


# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=50)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    cover_url = models.URLField(null=True, blank=True)
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_DEFAULT, default=1)
    public = models.BooleanField(default=False)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    saved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save_cover(self, html_str):
        result = async_convert.delay(html_str)
        url = result.get(timeout=20)
        if not self.cover_url:
            self.cover_url = url

notes/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import Note
from .widgets import DivTextarea
from .utils import check_note



class NoteForm(forms.ModelForm):
    text = forms.CharField(widget=DivTextarea(attrs={'id': 'editor'}))

    class Meta:
        model = Note
        fields = ['title','text']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(NoteForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(NoteForm, self).save(commit=False)
        instance.author = self.user
        instance.save_cover(self.cleaned_data.get("text"))
        if commit:
            instance.save()
        return instance



class UserProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'profile_photo', 'phone', 
                            'short_about', 'about', 'resume', 'intro_url', 'username', 'email']

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from .forms import NoteForm, UserProfileForm
from .models import Note, BookMarked
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import Q
from django.http.response import JsonResponse, Http404
from .utils import check_bookmark, check_note


# Create your views here.
class NoteCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = 'accounts:register'
    form_class = NoteForm
    model = Note
    template_name = 'note_create.html'
    success_url = reverse_lazy('note:manage')

    def form_valid(self, form):
        if check_note(self.request.user.username):
            return super().form_valid(form)
        else:
            return JsonResponse({'error': True})

    def get_form_kwargs(self):
        kwargs = super(NoteCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Create Note"
        data['profile_photo'] = self.request.user.profile_photo
        return data


class NoteUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = 'accounts:register'
    form_class = NoteForm
    model = Note
    template_name = 'note_update.html'
    success_url = reverse_lazy('note:manage')

    def get_form_kwargs(self):
        kwargs = super(NoteUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Update Note"
        data['profile_photo'] = self.request.user.profile_photo
        return data

    def get_object(self, queryset=None):
        if not self.request.user.is_superuser:
            return get_object_or_404(Note, uuid=self.kwargs.get('uuid'), author=self.request.user)
        return get_object_or_404(Note, uuid=self.kwargs.get('uuid'))



class NoteDetailView(LoginRequiredMixin, generic.DetailView):
    login_url = 'accounts:register'
    model = Note
    template_name = 'note_detail.html'
    context_object_name = 'note'
    
    def get_object(self, queryset=None):
        return get_object_or_404(Note, uuid=self.kwargs.get('uuid'))


class NotesManager(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        notes = Note.objects.filter(author=self.request.user)
        return render(request, 'note_manager.html', {'notes': notes, 'title': 'Manage Notes', 'profile_photo': self.request.user.profile_photo})

    def post(self, request):
        result = Note.objects.filter(author=self.request.user)
        query = request.POST.get('q')
        if query:
            if not request.user.is_superuser:
                result = Note.objects.filter(Q(title__icontains=query) | Q(text__icontains=query), author=self.request.user)
            result = Note.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
        return render(request, 'note_manager.html', {'notes': result, 'title': 'Manage Notes', 'profile_photo': self.request.user.profile_photo})



class FindUsers(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts:register'
    model = Note
    template_name = 'note_users.html'
    context_object_name = 'users_note'


    def get_queryset(self):
        # query = self.kwargs.get('q', None)
        query = self.request.GET.get('q', None)
        if query:
            result = self.model.objects.filter(
                Q(title__icontains=query) |
                Q(text__icontains=query) |
                Q(author__username=query)
            )
            if result:
                return result
        else:
            return self.model.objects.all().order_by('-pk')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Find Notes"
        data['profile_photo'] = self.request.user.profile_photo
        return data



class NoteBookMark(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts:register'
    model = get_user_model()
    template_name = 'note_bookmark.html'
    context_object_name = 'note_bookmark'


    def get_queryset(self):
        result = []
        query = self.request.GET.get('q', None)
        user = self.model.objects.get(pk=self.request.user.pk)
        note = user.bookmarked.all()
        for i in note:
            if query:
                if query in i.note.title or query in i.note.text:
                    result.append(i.note)
            else:
                result.append(i.note)
        return result

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Bookmarks"
        data['profile_photo'] = self.request.user.profile_photo
        return data



class NoteDeleteView(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        uuid = request.GET.get('uuid')
        try:
            note = get_object_or_404(Note, uuid=uuid, author=self.request.user)
            if note:
                note.delete()
                return JsonResponse({
                'success': True
            })
            return JsonResponse({
                'error': True
            })
        except Note.DoesNotExist:
            return JsonResponse({
                'error': 'Not Found'
            })



class UpdateProfile(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        try:
            user = get_user_model().objects.get(pk=request.user.pk)
        except get_user_model().DoesNotExist:
            return Http404()
        form = UserProfileForm(instance=user)
        return render(request, 'settings.html', {'form': form, 'title': 'Update Profile',
        'profile_photo': user.profile_photo})

    def post(self, request):
        user = get_user_model().objects.get(pk=request.user.pk)
        form = UserProfileForm(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('note:manage')

        return render(request, 'settings.html', {'form': form, 'title': 'Update Profile',
        'profile_photo': user.profile_photo})


def bookmark(request):
    if request.method == "GET":
        cr = request.GET.get("cr")
        uuid = request.GET.get("uuid")
        note = Note.objects.get(uuid=uuid)
        if cr == "create":
            if check_bookmark(request.user.username):
                BookMarked.objects.create(
                    user=request.user,
                    note=note
                )
                return JsonResponse({
                    'create_success': True
                })
            else:
                return JsonResponse({
                    'error': 'You cannot add bookmarks more than 10 times'
                })
        elif cr == "remove":
            bk = BookMarked.objects.get(
                user=request.user,
                note=note
            )
            bk.delete()
            return JsonResponse({
                'remove_success': True
            })



def pub_note(request):
    if request.method == "GET":
        cr = request.GET.get("cr")
        uuid = request.GET.get("uuid")
        note = Note.objects.get(uuid=uuid)
        if note.author == request.user:
            if cr == "create":
                note.public = True
                note.save()
                return JsonResponse({
                    'create_success': True
                })
            elif cr == "remove":
                note.public = False
                note.save()
                return JsonResponse({
                    'remove_success': True
                })
        else:
            return JsonResponse({
                'error': "You cannot public the note that you arent owned"
            })


def donate(request):
    return render(request, 'donate.html', {'title': "Donate US", "profile_photo": request.user.profile_photo})


class NotesStats(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        user = get_user_model().objects.get(pk=request.user.pk)
        user_notes_count = user.note_set.all().count()
        user_bookmarks = user.bookmarked.all().count()
        all_bookmarks = BookMarked.objects.all().count()
        all_notes = Note.objects.all().count()
        all_users = get_user_model().objects.all().count()
        return render(
            request,
            'stats.html',
            {
                'user_notes_count': user_notes_count,
                'user_bookmarks': user_bookmarks,
                'all_notes': all_notes,
                'all_users': all_users,
                'all_bookmarks': all_bookmarks
            })



class UsersProfile(LoginRequiredMixin, generic.DetailView):
    login_url = 'accounts:register'
    model = get_user_model()
    template_name = 'profile.html'
    context_object_name = 'profile'
    
    def get_object(self, queryset=None):
        return get_object_or_404(get_user_model(), username=self.kwargs.get('username'))

notes/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.js" integrity="sha512-Lii3WMtgA0C0qmmkdCpsG0Gjr6M0ajRyQRQSbTF6BsrVh/nhZdHpVZ76iMIPvQwz1eoXC3DmAg9K51qT5/dEVg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'ckeditor/build/ckeditor.js' %}"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{{title}} | D-NOTE</title>
</head>

<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
        {% if profile_photo %}
        <div class="header_img"><img src="{{profile_photo}}"></div>
        {% else %}
        <div class="header_img"> <img src="{% static 'images/avatar.png' %}" alt=""> </div>
        {% endif %}
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div> <a href="#" class=" nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">D-NOTE</span> </a>
                <div class="nav_list">
                    {% if request.path == '/manage/' %}
                    <a href="{% url 'note:manage' %}" class="nav_link active"> <i class='bx bx-grid-alt nav_icon'></i>
                        <span class="nav_name">Dashboard</span> </a>
                    {% else %}
                    <a href="{% url 'note:manage' %}" class="nav_link"> <i class='bx bx-grid-alt nav_icon'></i>
                        <span class="nav_name">Dashboard</span> </a>
                    {% endif %}
                    {% if request.path == '/' %}
                    <a href="{% url 'note:create' %}" class="nav_link active"> <i class='bx bx-message-square-detail nav_icon'></i> <span class="nav_name">Notes</span></a>
                    {% else %}
                    <a href="{% url 'note:create' %}" class="nav_link"> <i class='bx bx-message-square-detail nav_icon'></i> <span class="nav_name">Notes</span></a>
                    {% endif %}
                    {% if request.path == '/find/' %}
                    <a href="{% url 'note:find' %}" class="nav_link active"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users Notes</span></a>
                    {% else %}
                    <a href="{% url 'note:find' %}" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Users Notes</span></a>
                    {% endif %}
                    {% if request.path == '/bookmark/' %}
                    <a href="{% url 'note:bookmark' %}" class="nav_link active"> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Bookmark</span> </a>
                    {% else %}
                    <a href="{% url 'note:bookmark' %}" class="nav_link"> <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Bookmark</span> </a>
                    {% endif %}
                    {% if request.path == '/settings/' %}
                    <a href="{% url 'note:settings' %}" class="nav_link active"> <i class='bx bx-slider nav_icon'></i><span class="nav_name">Settings</span> </a>
                    {% else %}
                    <a href="{% url 'note:settings' %}" class="nav_link"> <i class='bx bx-slider nav_icon'></i><span class="nav_name">Settings</span> </a>
                    {% endif %}
                    {% if request.path == '/stats/' %}
                    <a href="{% url 'note:stats' %}" class="nav_link active"> <i class='bx bx-bar-chart-alt-2 nav_icon'></i> <span class="nav_name">Stats</span> </a>
                    {% else %}
                    <a href="{% url 'note:stats' %}" class="nav_link"> <i class='bx bx-bar-chart-alt-2 nav_icon'></i> <span class="nav_name">Stats</span> </a>
                    {% endif %}
                </div>
            </div>
            <a href="" type="button" class="nav_link" data-bs-toggle="modal" data-bs-target="#exampleModalLogout">
                <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Logout</span> </a>
        </nav>
    </div>
    <!--Container Main start-->
    <div class="height-100 bg-light">
        <div id="msg"></div>

        <div class="modal fade" id="exampleModalLogout" tabindex="-1" aria-labelledby="exampleModalLabelLogout" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabelLogout">Logout</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>
                            if you logout, your account will be removed
                            <b>Are you sure?</b>
                        </p>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button style="float: left;" type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <a href="{% url 'accounts:logout'  %}" style="float: right;" type="button" class="btn btn-success">Sure</a>
                    </div>
                </div>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
        <a href="{% url 'note:create' %}" style="position:absolute;bottom:5px;left:5px;margin:0;padding:5px 3px;"><i class="fas fa-plus-circle fa-3x"></i></a>
    </div>

</body>

</html>