accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('send-code/', views.send_code, name='scode'),
    path('logout/', views.logout, name="logout")
    # path('profile/detail/', views.UpdateProfile.as_view(), name='profile_detail'),
]

notes/urls.py
from django.urls import path
from . import views


app_name = 'note'

urlpatterns = [
    path('', views.NoteCreateView.as_view(), name='create'),
    path('manage/', views.NotesManager.as_view(), name='manage'),
    path('update/<uuid>/', views.NoteUpdateView.as_view(), name='update'),
    path('detail/<uuid>/', views.NoteDetailView.as_view(), name='detail'),
    path('delete/', views.NoteDeleteView.as_view(), name='delete'),
    path('settings/', views.UpdateProfile.as_view(), name='settings'),
    path('find/', views.FindUsers.as_view(), name='find'),
    path('profile/<str:username>/', views.UsersProfile.as_view(), name="user-profile"),
    path('note/pub/', views.pub_note, name='pub-note'),
    path('bookmark/', views.NoteBookMark.as_view(), name='bookmark'),
    path('bookmark/add/', views.bookmark, name='add-bookmark'),
    path('stats/', views.NotesStats.as_view(), name='stats'),
    path('donate/', views.donate, name="donate"),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('bigdevil/url/admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from .utils import upload_photo_path, upload_resume_path
from django.urls import reverse_lazy



# Create your models here.
class User(AbstractUser):
    first_name = models.CharField(max_length=100, blank=False, null=False)
    last_name = models.CharField(max_length=100, blank=False, null=False)
    ip_addr = models.GenericIPAddressField(null=True)
    user_agent = models.CharField(max_length=250, null=True)
    profile_photo = models.ImageField(upload_to=upload_photo_path, blank=True, null=True)
    phone_regex = RegexValidator(regex='^(0|0098|\+98)9(0[1-5]|[1 3]\d|2[0-2]|98)\d{7}$', message='You should enter the correct phone numgber.')
    phone = models.CharField(max_length=11, validators=[phone_regex], blank=True, null=True)
    short_about = models.CharField(max_length=170)
    about = models.TextField(max_length=400, blank=True, null=True)
    resume = models.FileField(upload_to=upload_resume_path, blank=True, null=True)
    intro_url = models.URLField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.username

    def get_full_name(self):
        return first_name + last_name

    def get_absolute_url(self):
        return reverse_lazy("note:user-profile", kwargs={"username": self.username})

accounts/forms.py
from django.core.validators import ValidationError
from django.core.cache import cache
from django import forms
from django.contrib.auth import get_user_model



class UserRegistrationForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField(widget=forms.EmailInput())
    code = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirm = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        code = self.cleaned_data.get('code')
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        main_code = cache.get(email)
        if main_code:
            if int(main_code) == int(code):
                if not get_user_model().objects.filter(email=email).count() > 0:
                    if self.request.META.get("HTTP_X_FORWARDED_FOR"):
                        ip_addr = self.request.META.get("HTTP_X_FORWARDED_FOR")
                    else:
                        ip_addr = self.request.META.get("HTTP_REMOTE_ADDR")
                    user = get_user_model().objects.create(
                        email=email,
                        username=username,
                        ip_addr=ip_addr,
                        user_agent=self.request.META.get("HTTP_USER_AGENT")
                    )
                    if password == password_confirm:
                        user.set_password(password_confirm)
                        user.is_active = True
                        user.save()
                        cache.delete(email)
                    else:
                        self.add_error("password_confirm", "Passwords do not match")
                else:
                    self.add_error("email", "This email address is already exist.")
            else:
                self.add_error("code", "code is invalid")
        else:
            self.add_error("code", "code is expired")


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

accounts/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .forms import UserLoginForm, UserRegistrationForm
from django.http.response import JsonResponse
from .tasks import sendemail
from django.core.cache import cache
from .utils import random_code
from django.contrib.auth import authenticate, login, logout, get_user_model



# Create your views here.
class Register(generic.View):
    def get(self, request):
        form = UserRegistrationForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = UserRegistrationForm(request.POST, request=request)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('note:manage')
        return render(request, 'register.html', {'form': form})



class Login(generic.View):
    def post(self, request):
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return JsonResponse({
                'success': True
            })
        return JsonResponse({
            'error': 'user does not exist'
        })


def logout(request):
    try:
        user = get_user_model().objects.get(pk=request.user.pk)
        user.delete()
        logout(request)
    except get_user_model().DoesNotExist:
        logout(request)



def send_code(request):
    email = request.GET.get("email")
    code = random_code()
    cache.set(email, code, 2600)
    subject = "Verify EmailAddress"
    html_text = f"""
    <h2>Hello dear {email}</h2>
    <p>Welcome to our website</p>
    <p>here is your code: <b>{code}</b></p>
    <b>Thanks for choosing us</b>
    """
    sendemail.delay(subject, html_text, email)
    return JsonResponse({
        'success': True,
    })

accounts/templates/register.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Registration | D-NOTE</title>
</head>

<body class="full">
    <div class="msg"></div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login Now</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form class="form-group" action="">
                        <div>
                            <label for="username">Username: </label>
                            <input class="form-control" type="text" name="username" id="username">
                        </div>
                        <div>
                            <label for="password">Password</label>
                            <input class="form-control" type="password" name="password" id="password">
                        </div>
                    </form>
                </div>
                <div class="modal-footer justify-content-between">
                    <button style="float: left;" type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    <button id="submit" style="float: right;" type="button" class="btn btn-ppurple">Login</button>
                </div>
            </div>
        </div>
    </div>


    <div class="container full my-auto vertical-center">
        <div class="card col-lg-6 col-md-8 col-sm-12 col-xs-12">
            <div class="card-header">
                <h5 class="card-title">Register Your Account</h5>
            </div>
            <div class="card-body">
                <form id="myform" class="form-group" method="POST">
                    <div class="row">
                        {% csrf_token %}
                        <div class="col-lg-6 col-md- col-sm-12 col-xs-12">
                            <label for="id_username">{{form.username.label}} :</label>
                            {% render_field form.username class+="form-control" %}
                            <div class="is-invalid">{{form.username.errors}}</div>
                        </div>
                        <div class="col-lg-6 col-md- col-sm-12 col-xs-12">
                            <label for="id_email">{{form.email.label}} :</label>
                            {% render_field form.email class+="form-control" %}
                            <div class="is-invalid">{{form.email.errors}}</div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="row">
                                <div class="code col-lg-10 col-md-8 col-sm-8 col-xs-8">
                                    <label for="id_code">{{form.code.label}} :</label>
                                    {% render_field form.code class+="form-control" %}
                                    <div class="is-invalid">{{form.code.errors}}</div>
                                </div>
                                <div class="code-btn col-lg-2 col-md-4 col-sm-4 col-xs-4 vertical-center">
                                    <a id="scode" class="xbtn btn btn-ppurple"><i id="change-icon" class='bx bxs-send'></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <label for="id_password">{{form.password.label}} :</label>
                            {% render_field form.password class+="form-control" %}
                            <div class="is-invalid">{{form.password.errors}}</div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="row">
                                <div class="col-lg-10 col-md-8 col-sm-8 col-xs-8">
                                    <label for="id_password_confirm">{{form.password_confirm.label}} :</label>
                                    {% render_field form.password_confirm class+="form-control" %}
                                    <div class="is-invalid">{{form.password_confirm.errors}}</div>
                                </div>
                                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 vertical-center">
                                    <a onclick="showp()" class="xbtn btn btn-secondary"><i class='bx bx-at'></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <p class="card-text"></p>
                <input form="myform" type="submit" href="{% url 'accounts:register' %}" style="float: right;" class="btn btn-ppurple" value="Register">
                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">Login</button>
            </div>
        </div>
    </div>
</body>


<script>
    $("#scode").click(() => {
        var email = $("#id_email").val()
        if (!email) {
            alert("Please fill email field")
        }
        $("#change-icon").removeClass().addClass('bx bx-check')
        $("#scode").removeClass("btn-ppurple").addClass("btn-success")
        $.ajax({
            url: "{% url 'accounts:scode' %}",
            type: "GET",
            data: {
                'email': email,
            },
            success: (r) => {
                $("#msg").addClass("alert alert-success").html("Email has been sent to your box.")
                setTimeout(() => {
                    $("#msg").removeClass("alert alert-success").html('')
                }, 5000);
            }

        })
    })



    $("#submit").click(() => {
        $.ajax({
            url: "{% url 'accounts:login' %}",
            type: "POST",
            data: {
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                'username': $("#username").val(),
                'password': $("#password").val(),
            },
            success: (result) => {
                if (result.success) {
                    $("#msg").addClass("alert alert-success").html("You have been logged in, you'll be go on your dashboard automatically.")
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-success").html('')
                    }, 5000);
                    window.location.href = "{% url 'note:manage' %}"
                }
            }
        })
    })


    function showp() {
        var x = document.getElementById("id_password");
        var y = document.getElementById("id_password_confirm")
        if (x.type === "password" && y.type === "password") {
            x.type = "text";
            y.type = "text";
        } else {
            x.type = "password";
            y.type = "password"
        }
    }
</script>


</html>