notes/urls.py
from django.urls import path
from . import views


app_name = 'note'

urlpatterns = [
    path('', views.NoteCreateView.as_view(), name='create'),
    path('manage/', views.NotesManager.as_view(), name='manage'),
    path('update/<uuid>/', views.NoteUpdateView.as_view(), name='update'),
    path('detail/<uuid>/', views.NoteDetailView.as_view(), name='detail'),
    path('delete/', views.NoteDeleteView.as_view(), name='delete'),
    path('settings/', views.UpdateProfile.as_view(), name='settings'),
    path('find/', views.FindUsers.as_view(), name='find'),
    path('profile/<str:username>/', views.UsersProfile.as_view(), name="user-profile"),
    path('note/pub/', views.pub_note, name='pub-note'),
    path('bookmark/', views.NoteBookMark.as_view(), name='bookmark'),
    path('bookmark/add/', views.bookmark, name='add-bookmark'),
    path('stats/', views.NotesStats.as_view(), name='stats'),
    path('donate/', views.donate, name="donate"),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('bigdevil/url/admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from .utils import upload_photo_path, upload_resume_path
from django.urls import reverse_lazy



# Create your models here.
class User(AbstractUser):
    first_name = models.CharField(max_length=100, blank=False, null=False)
    last_name = models.CharField(max_length=100, blank=False, null=False)
    ip_addr = models.GenericIPAddressField(null=True)
    user_agent = models.CharField(max_length=250, null=True)
    profile_photo = models.ImageField(upload_to=upload_photo_path, blank=True, null=True)
    phone_regex = RegexValidator(regex='^(0|0098|\+98)9(0[1-5]|[1 3]\d|2[0-2]|98)\d{7}$', message='You should enter the correct phone numgber.')
    phone = models.CharField(max_length=11, validators=[phone_regex], blank=True, null=True)
    short_about = models.CharField(max_length=170)
    about = models.TextField(max_length=400, blank=True, null=True)
    resume = models.FileField(upload_to=upload_resume_path, blank=True, null=True)
    intro_url = models.URLField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.username

    def get_full_name(self):
        return first_name + last_name

    def get_absolute_url(self):
        return reverse_lazy("note:user-profile", kwargs={"username": self.username})

notes/models.py
from django.db import models
from django.conf import settings
from .tasks import async_convert
from django.core.files import File
import uuid
import os


CODE_LANGUAGE_CHOICES = (
    (1, 'Plain Text'),
    (2, 'Programming Language Code'),
)


class BookMarked(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='bookmarked')
    note = models.OneToOneField('Note', on_delete=models.CASCADE, related_name='bookmarked')


# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=50)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    cover_url = models.URLField(null=True, blank=True)
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_DEFAULT, default=1)
    public = models.BooleanField(default=False)
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    saved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save_cover(self, html_str):
        result = async_convert.delay(html_str)
        url = result.get(timeout=20)
        if not self.cover_url:
            self.cover_url = url

accounts/forms.py
from django.core.validators import ValidationError
from django.core.cache import cache
from django import forms
from django.contrib.auth import get_user_model



class UserRegistrationForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField(widget=forms.EmailInput())
    code = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    password_confirm = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        code = self.cleaned_data.get('code')
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        main_code = cache.get(email)
        if main_code:
            if int(main_code) == int(code):
                if not get_user_model().objects.filter(email=email).count() > 0:
                    if self.request.META.get("HTTP_X_FORWARDED_FOR"):
                        ip_addr = self.request.META.get("HTTP_X_FORWARDED_FOR")
                    else:
                        ip_addr = self.request.META.get("HTTP_REMOTE_ADDR")
                    user = get_user_model().objects.create(
                        email=email,
                        username=username,
                        ip_addr=ip_addr,
                        user_agent=self.request.META.get("HTTP_USER_AGENT")
                    )
                    if password == password_confirm:
                        user.set_password(password_confirm)
                        user.is_active = True
                        user.save()
                        cache.delete(email)
                    else:
                        self.add_error("password_confirm", "Passwords do not match")
                else:
                    self.add_error("email", "This email address is already exist.")
            else:
                self.add_error("code", "code is invalid")
        else:
            self.add_error("code", "code is expired")


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

notes/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import Note
from .widgets import DivTextarea
from .utils import check_note



class NoteForm(forms.ModelForm):
    text = forms.CharField(widget=DivTextarea(attrs={'id': 'editor'}))

    class Meta:
        model = Note
        fields = ['title','text']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(NoteForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(NoteForm, self).save(commit=False)
        instance.author = self.user
        instance.save_cover(self.cleaned_data.get("text"))
        if commit:
            instance.save()
        return instance



class UserProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'profile_photo', 'phone', 
                            'short_about', 'about', 'resume', 'intro_url', 'username', 'email']

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from .forms import NoteForm, UserProfileForm
from .models import Note, BookMarked
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import Q
from django.http.response import JsonResponse, Http404
from .utils import check_bookmark, check_note


# Create your views here.
class NoteCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = 'accounts:register'
    form_class = NoteForm
    model = Note
    template_name = 'note_create.html'
    success_url = reverse_lazy('note:manage')

    def form_valid(self, form):
        if check_note(self.request.user.username):
            return super().form_valid(form)
        else:
            return JsonResponse({'error': True})

    def get_form_kwargs(self):
        kwargs = super(NoteCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Create Note"
        data['profile_photo'] = self.request.user.profile_photo
        return data


class NoteUpdateView(LoginRequiredMixin, generic.UpdateView):
    login_url = 'accounts:register'
    form_class = NoteForm
    model = Note
    template_name = 'note_update.html'
    success_url = reverse_lazy('note:manage')

    def get_form_kwargs(self):
        kwargs = super(NoteUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Update Note"
        data['profile_photo'] = self.request.user.profile_photo
        return data

    def get_object(self, queryset=None):
        if not self.request.user.is_superuser:
            return get_object_or_404(Note, uuid=self.kwargs.get('uuid'), author=self.request.user)
        return get_object_or_404(Note, uuid=self.kwargs.get('uuid'))



class NoteDetailView(LoginRequiredMixin, generic.DetailView):
    login_url = 'accounts:register'
    model = Note
    template_name = 'note_detail.html'
    context_object_name = 'note'
    
    def get_object(self, queryset=None):
        return get_object_or_404(Note, uuid=self.kwargs.get('uuid'))


class NotesManager(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        notes = Note.objects.filter(author=self.request.user)
        return render(request, 'note_manager.html', {'notes': notes, 'title': 'Manage Notes', 'profile_photo': self.request.user.profile_photo})

    def post(self, request):
        result = Note.objects.filter(author=self.request.user)
        query = request.POST.get('q')
        if query:
            if not request.user.is_superuser:
                result = Note.objects.filter(Q(title__icontains=query) | Q(text__icontains=query), author=self.request.user)
            result = Note.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
        return render(request, 'note_manager.html', {'notes': result, 'title': 'Manage Notes', 'profile_photo': self.request.user.profile_photo})



class FindUsers(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts:register'
    model = Note
    template_name = 'note_users.html'
    context_object_name = 'users_note'


    def get_queryset(self):
        # query = self.kwargs.get('q', None)
        query = self.request.GET.get('q', None)
        if query:
            result = self.model.objects.filter(
                Q(title__icontains=query) |
                Q(text__icontains=query) |
                Q(author__username=query)
            )
            if result:
                return result
        else:
            return self.model.objects.all().order_by('-pk')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Find Notes"
        data['profile_photo'] = self.request.user.profile_photo
        return data



class NoteBookMark(LoginRequiredMixin, generic.ListView):
    login_url = 'accounts:register'
    model = get_user_model()
    template_name = 'note_bookmark.html'
    context_object_name = 'note_bookmark'


    def get_queryset(self):
        result = []
        query = self.request.GET.get('q', None)
        user = self.model.objects.get(pk=self.request.user.pk)
        note = user.bookmarked.all()
        for i in note:
            if query:
                if query in i.note.title or query in i.note.text:
                    result.append(i.note)
            else:
                result.append(i.note)
        return result

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = "Bookmarks"
        data['profile_photo'] = self.request.user.profile_photo
        return data



class NoteDeleteView(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        uuid = request.GET.get('uuid')
        try:
            note = get_object_or_404(Note, uuid=uuid, author=self.request.user)
            if note:
                note.delete()
                return JsonResponse({
                'success': True
            })
            return JsonResponse({
                'error': True
            })
        except Note.DoesNotExist:
            return JsonResponse({
                'error': 'Not Found'
            })



class UpdateProfile(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        try:
            user = get_user_model().objects.get(pk=request.user.pk)
        except get_user_model().DoesNotExist:
            return Http404()
        form = UserProfileForm(instance=user)
        return render(request, 'settings.html', {'form': form, 'title': 'Update Profile',
        'profile_photo': user.profile_photo})

    def post(self, request):
        user = get_user_model().objects.get(pk=request.user.pk)
        form = UserProfileForm(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('note:manage')

        return render(request, 'settings.html', {'form': form, 'title': 'Update Profile',
        'profile_photo': user.profile_photo})


def bookmark(request):
    if request.method == "GET":
        cr = request.GET.get("cr")
        uuid = request.GET.get("uuid")
        note = Note.objects.get(uuid=uuid)
        if cr == "create":
            if check_bookmark(request.user.username):
                BookMarked.objects.create(
                    user=request.user,
                    note=note
                )
                return JsonResponse({
                    'create_success': True
                })
            else:
                return JsonResponse({
                    'error': 'You cannot add bookmarks more than 10 times'
                })
        elif cr == "remove":
            bk = BookMarked.objects.get(
                user=request.user,
                note=note
            )
            bk.delete()
            return JsonResponse({
                'remove_success': True
            })



def pub_note(request):
    if request.method == "GET":
        cr = request.GET.get("cr")
        uuid = request.GET.get("uuid")
        note = Note.objects.get(uuid=uuid)
        if note.author == request.user:
            if cr == "create":
                note.public = True
                note.save()
                return JsonResponse({
                    'create_success': True
                })
            elif cr == "remove":
                note.public = False
                note.save()
                return JsonResponse({
                    'remove_success': True
                })
        else:
            return JsonResponse({
                'error': "You cannot public the note that you arent owned"
            })


def donate(request):
    return render(request, 'donate.html', {'title': "Donate US", "profile_photo": request.user.profile_photo})


class NotesStats(LoginRequiredMixin, generic.View):
    login_url = 'accounts:register'

    def get(self, request):
        user = get_user_model().objects.get(pk=request.user.pk)
        user_notes_count = user.note_set.all().count()
        user_bookmarks = user.bookmarked.all().count()
        all_bookmarks = BookMarked.objects.all().count()
        all_notes = Note.objects.all().count()
        all_users = get_user_model().objects.all().count()
        return render(
            request,
            'stats.html',
            {
                'user_notes_count': user_notes_count,
                'user_bookmarks': user_bookmarks,
                'all_notes': all_notes,
                'all_users': all_users,
                'all_bookmarks': all_bookmarks
            })



class UsersProfile(LoginRequiredMixin, generic.DetailView):
    login_url = 'accounts:register'
    model = get_user_model()
    template_name = 'profile.html'
    context_object_name = 'profile'
    
    def get_object(self, queryset=None):
        return get_object_or_404(get_user_model(), username=self.kwargs.get('username'))

notes/templates/note_bookmark.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<ol class="tag breadcrumb d-flex justify-content-between">
    <li><a href="#">Bookmarks</a></li>
    <form class="d-flex" method="GET" action="{% url 'note:bookmark' %}"><input class="form-control" placeholder="Search..." style="height: 30px;" type="search" name="q"><button type="submit" style="height: 30px;" class="btn btn-success"><i class='bx bx-search-alt'></i></button></form>
</ol>

<style>
    .card {
        margin: 5px 5px 5px 5px;
    }
</style>


<div class="row justify-content-center">
    {% for i in note_bookmark %}
    <div id="{{i.uuid}}" class="card col-lg-4 col-md-6 col-sm-10" style="width: 18rem;">
        {% if i.cover_url %}
        <img src="{{i.cover_url}}" class="card-img-top" width="100px" height="100px" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{i.title}}</h5>

            <div class="d-flex justify-content-between">
                <small class="text-secondary">By <a href="{{i.author.get_absolute_url}}">{{i.author.username}}</a></small>
                <div>
                    {% if i.author == request.user %}
                    {% if not i.public %}
                    <a onclick="pub('{{i.uuid}}', 'create')" href="#"><i id="{{i.uuid}}-pub" class='bx bx-globe'></i></a>
                    {% else %}
                    <a onclick="pub('{{i.uuid}}', 'remove')" href="#"><i id="{{i.uuid}}-pub" class='bx bx-globe text-success'></i></a>
                    {% endif %}
                    {% endif %}
                    {% if not i.bookmarked.user == request.user %}
                    <a onclick="bookmark('{{i.uuid}}', 'create')" href="#"><i id="{{i.uuid}}-book" class='bx bx-bookmark'></i></a>
                    {% else %}
                    <a onclick="bookmark('{{i.uuid}}', 'remove')" href="#"><i id="{{i.uuid}}-book" class='bx bxs-bookmark'></i></a>
                    {% endif %}
                </div>
            </div>
            <a href="{% url 'note:detail' i.uuid %}" class="btn btn-ppurple">View</a>
            <a href="{% url 'note:update' i.uuid %}" class="btn btn-secondary">Update</a>
            <a onclick="delete_note('{{i.uuid}}')" class="btn btn-danger">Delete</a>

        </div>
    </div>
    {% empty %}
    <p class="text-center text-bold">There is no any notes in here, lets create once.</p>
    {% endfor %}
</div>





<script>
    function delete_note(uuid) {
        $.ajax({
            url: "{% url 'note:delete' %}",
            type: "GET",
            data: {
                'uuid': uuid
            },
            success: (result) => {
                if (result.success) {
                    $("#msg").addClass('alert alert-success').html('The note has been deleted successfully')
                    // window.location.reload()
                    $(`#${uuid}`).hide()
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-success").html('')
                    }, 5000);

                }
            }
        })
    }

    function bookmark(uuid, cr) {
        $.ajax({
            url: "{% url 'note:add-bookmark' %}",
            type: "GET",
            data: {
                'uuid': uuid,
                'cr': cr,
            },
            success: (result) => {
                if (result.create_success) {
                    $("#msg").addClass('alert alert-success').html('The note has been bookmarked successfully')
                    // $(`#${uuid}-book`).parent().html(`<a onclick="bookmark(${uuid}, 'remove')" href="#"><i id='${uuid}-book' class='bx bxs-bookmark'></i></a>`)
                    window.location.reload()
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-success").html('')
                    }, 5000);
                } else if (result.remove_success) {
                    $("#msg").addClass('alert alert-danger').html('The note has been removed from bookmarked notes')
                    window.location.reload()
                    // $(`#${uuid}-book`).parent().html(`<a onclick="bookmark(${uuid}, 'create')" href="#"><i id='${uuid}-book' class='bx bx-bookmark'></i></a>`)
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-danger").html('')
                    }, 5000);
                }
            }
        })
    }



    function pub(uuid, cr) {
        $.ajax({
            url: "{% url 'note:pub-note' %}",
            type: "GET",
            data: {
                'uuid': uuid,
                'cr': cr,
            },
            success: (result) => {
                if (result.create_success) {
                    $("#msg").addClass('alert alert-success').html('The note has been publiced successfully')
                    window.location.reload()
                    // $(`#${uuid}-pub`).parent().html(`<a onclick="pub("${uuid}", 'remove')" href="#"><i id="${uuid}-pub" class='bx bx-globe text-success'></i></a>`)
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-success").html('')
                    }, 5000);
                } else if (result.remove_success) {
                    $("#msg").addClass('alert alert-danger').html('The note has been private successfully')
                    // $(`#${uuid}-pub`).parent().html(`<a onclick="pub("${uuid}", 'create')" href="#"><i id="${uuid}-pub" class='bx bx-globe'></i></a>`)
                    window.location.reload()
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-danger").html('')
                    }, 5000);
                } else if (result.error) {
                    $("#msg").addClass('alert alert-danger').html(`${result.error}`)
                    setTimeout(() => {
                        $("#msg").removeClass("alert alert-danger").html('')
                    }, 5000);
                }
            }
        })
    }
</script>
{% endblock content %}

notes/templates/note_create.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}

<form id="form" class="form-group">{% csrf_token %}
    <ol class="tag breadcrumb justify-content-between">
        <div class="col-xs-8 col-sm-8 col-md-6 col-lg-4 d-flex justify-content-start">
            <label class="col col-xs-2 vertical-center" for="id_title">Create New Note: </label>
            {% render_field form.title class+="form-control col col-xs-10" placeholder="Enter title here..." %}
            {% if form.title.errors %}
            <div class="is-invalid text-danger">{{ form.title.errors }}</div>
            {% endif %}
        </div>
        <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2">
            <input id="sbmt" class="sbtn form-control btn btn-danger" type="submit" value="Save Note">
        </div>
    </ol>
    {% if form.text.errors %}
    <div class="is-invalid text-danger">{{ form.text.errors }}</div>
    {% endif %}
    <small>Select your text and set a style</small>
    {% render_field form.text class+="form-control mt-4" id="editor" %}
</form>


<script>
    // BalloonEditor
    BalloonEditor
        .create(document.querySelector('#editor'))
        .catch(error => {
            console.error(error);
        });



    // Handling ajax form
    $('#form').on('submit', function(e) {
        e.preventDefault();
        text = $("#editor").html();
        if (text === "<p><br data-cke-filler=\"true\"></p>") {
            alert("Sorry, you should write something on editor to save it.")
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'note:create' %}",
                data: {
                    'title': $("#id_title").val(),
                    'text': $("#editor").html(),
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function(data) {
                    if (!data.error) {
                        $("#msg").addClass("alert alert-success").html("Your note created successfully, Go on <a href=\'{% url 'note:manage' %}\'>Dashboard</a> to manage it.")
                        setTimeout(() => {
                            $("#msg").removeClass("alert alert-success").html('')
                        }, 5000);
                    } else {
                        alert("You cannot create more than 8 notes")

                    }
                },
            })
        }
    });
</script>


{% endblock content %}

notes/templates/note_detail.html
{{note.text| safe}}

notes/templates/profile.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}

<ol class="tag breadcrumb">
    <li><a href="#">{{profile.username}} Profile</a></li>
</ol>


<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="card">
            <div class="card-header">
                {% if profile.get_full_name %}
                {{profile.get_full_name}}
                {% else %}
                {{profile.username}}
                {% endif %}
            </div>
            <div class="card-body">
                <div class="col-lg-3 col-md-6 col-sm-10">
                    <label for="id_first_name">first_name: </label>
                    {{profile.first_name}}
                </div>
                <div class="col-lg-3 col-md-6 col-sm-10">
                    <label for="id_last_name">last_name: </label>
                    {{profile.last_name}}
                </div>
                <div class="col-lg-3 col-md-6 col-sm-10">
                    <label for="id_username">username :</label>
                    {{profile.username}}
                </div>
                <div class="col-lg-3 col-md-6 col-sm-10">
                    <label for="id_email">email :</label>
                    {{profile.email}}
                </div>
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <label for="id_profile_photo">profile_photo :</label>
                    <img class="img-rounded" src="{{profile.profile_photo.url}}" width="30px" height="30px">
                </div>
                <div class=" col-lg-6 col-md-8 col-sm-10">
                    <label for="id_resume">resume: </label>
                    {% if profile.resume %}
                    <a href="{{profile.resume.url}}">Download Resume</a>
                    {% else %}
                    <a>There isnt resume</a>
                    {% endif %}
                </div>
                <div class="col-lg-4 col-sm-12 col-md-6">
                    <label for="id_intro_url">intro url :</label>
                    {{profile.intro_url}}
                </div>
                <div class="col-lg-4 col-sm-12 col-md-6">
                    <label for="id_phone">phone :</label>
                    {{profile.phone}}
                </div>
                <div class="col-lg-4 col-sm-12 col-md-6">
                    <label for="id_short_about">short_about :</label>
                    {{profile.short_about}}
                </div>
                <div class="col-lg-10 col-sm-12 col-md-10">
                    <label for="id_about">about :</label>
                    {{profile.about}}
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

notes/templates/settings.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}

<ol class="tag breadcrumb">
    <li><a href="#">Settings</a></li>
</ol>


<div class="container-fluid">
    <form method="POST" class="form-group">
        <div class="row justify-content-center">
            {% csrf_token %}
            <div class="col-lg-3 col-md-6 col-sm-10">
                <label for="id_first_name">first_name</label>
                {% render_field form.first_name class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-10">
                <label for="id_last_name">last_name</label>
                {% render_field form.last_name class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-3 col-md-6 col-sm-10">
                <label for="id_username">username</label>
                {% render_field form.username class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-3 col-md-6 col-sm-10">
                <label for="id_email">email</label>
                {% render_field form.email class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-6 col-md-8 col-sm-10">
                <label for="id_profile_photo">profile_photo</label>
                {% render_field form.profile_photo class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-6 col-md-8 col-sm-10">
                <label for="id_resume">resume</label>
                {% render_field form.resume class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-4 col-sm-12 col-md-6">
                <label for="id_intro_url">intro_url</label>
                {% render_field form.intro_url class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-4 col-sm-12 col-md-6">
                <label for="id_phone">phone</label>
                {% render_field form.phone class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-4 col-sm-12 col-md-6">
                <label for="id_short_about">short_about</label>
                {% render_field form.short_about class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>

            </div>
            <div class="col-lg-10 col-sm-12 col-md-10">
                <label for="id_about">about</label>
                {% render_field form.about class+="form-control" %}
                <div class="is-invalid text-danger">{{ form.title.errors }}</div>
            </div>
        </div>
        <input style="float: right;" class="btn btn-ppurple" type="submit" value="Save">
    </form>
</div>



{% endblock content %}